### ISSUE TITLE
SfMovieRecordPlugin.dll caused an Access Violation (0xc0000005)

### ISSUE THREAD

**Issue by Darkirius** [SystemFriend/GPUVideoEncoder-Trial#1]
Hi. i'm use Unity 5.3.4f1.
OS Windows 10.

I get an error SfMovieRecordPlugin.dll caused an Access Violation (0xc0000005).
You can fix it?

**Comment by satoshi-maemoto** [comment]
@Darkirius 
Hi. I'm developer of this plugin.
I checked this plugin. 
it's worked fine. 
My environment is follow.
- Windows 10 Pro 1511 (OS build 10586.318)
- GPU: GeForce GTX 970

Can you tell me your environment?

**Comment by Darkirius** [comment]
[DxDiag.txt](https://github.com/SystemFriend/GPUVideoEncoder-Trial/files/290679/DxDiag.txt)

[error.txt](https://github.com/SystemFriend/GPUVideoEncoder-Trial/files/290682/error.txt)

**Comment by Darkirius** [comment]
https://drive.google.com/open?id=0B_V8lUHHF2uBWEdjOGxKRE5mekE
This test project.
Need a webcam.
Error after several attempts. A maximum of 10.
Control via a script Assets\test\ScriptController.cs

**Comment by Darkirius** [comment]
When you correct the issue?
If it works, I'm ready to buy.

**Comment by satoshi-maemoto** [comment]
Thank you for your information.
I will check this issue tomorrow.
Please wait a little.

**Comment by satoshi-maemoto** [comment]
@Darkirius 
Hi. I fixed this probrem probably.
Please check latest version.

Unity Asset Store version has problem yet.
but can work replase the MovieRecordCamera.cs.

Your information is very valuable.
Thank you!

**Comment by Darkirius** [comment]
GPUVideoEncoder : Unable to initialize nvenc H/W Encoder.
UnityEngine.Debug:Log(Object)
GPUVideoEncoder.MovieRecordCamera:SfMovieRecordPluginDebugCallBack(String) (at Assets/GPUVideoEncoder/Scripts/MovieRecordCamera.cs:24)
GPUVideoEncoder.SfMovieRecord:SfMR_StartMovieRecord(String, String, IntPtr, Int32, Boolean, UInt64)
GPUVideoEncoder.SfMovieRecord:StartMovieRecord(String, String, IntPtr, Int32, Boolean, UInt64) (at Assets/GPUVideoEncoder/Scripts/SfMovieRecord.cs:83)
GPUVideoEncoder.MovieRecordCamera:StartMovieRecord() (at Assets/GPUVideoEncoder/Scripts/MovieRecordCamera.cs:45)

**Comment by Darkirius** [comment]
GPUVideoEncoderException: Unable to initialize nvenc H/W Encoder.
GPUVideoEncoder.SfMovieRecord.StartMovieRecord (System.String outputPath, System.String fileTitle, IntPtr texture, Int32 fps, Boolean withAudio, UInt64 audioDeviceIndex) (at Assets/GPUVideoEncoder/Scripts/SfMovieRecord.cs:85)
GPUVideoEncoder.MovieRecordCamera.StartMovieRecord () (at Assets/GPUVideoEncoder/Scripts/MovieRecordCamera.cs:45)

**Comment by satoshi-maemoto** [comment]
@Darkirius 
Hi. Is this error occurs everytime? or sometime?

**Comment by Darkirius** [comment]
Often. When I change my code and press Play.

**Comment by satoshi-maemoto** [comment]
@Darkirius 
I was update to this branch.
https://github.com/SystemFriend/GPUVideoEncoder-Trial/tree/issue/1

Please check and tell me the results.

**Comment by Darkirius** [comment]
Cool!
I'm happy.

How to record sound with the camera AudioListener component?

**Comment by satoshi-maemoto** [comment]
@Darkirius 
OK!
Thank you for your sample project.
It helped me to improve this plugin.

Please refer readme P3  "Audio Recording".

https://github.com/SystemFriend/GPUVideoEncoder-Trial/blob/master/SfMovieRecordDevUnity/Assets/GPUVideoEncoder/readme.pdf 

Thank you.

**Comment by Darkirius** [comment]
Green line bottom in video for trial-version?

**Comment by satoshi-maemoto** [comment]
@Darkirius 
This plugin supports 1920x1080 RenderTexrure now.
but I want support another resolution. #7
