### ISSUE TITLE
Color tone.

### ISSUE THREAD

**Issue by Darkirius** [SystemFriend/GPUVideoEncoder-Trial#10]
Color tone don't fix. I'm want to buy plugin. And i want see fix. 
[SfMovieRecordDevUnity_test.zip](https://github.com/SystemFriend/GPUVideoEncoder-Trial/files/327517/SfMovieRecordDevUnity_test.zip)

**Comment by satoshi-maemoto** [comment]
Hi @Darkirius 

Please check this brunch.
https://github.com/SystemFriend/GPUVideoEncoder-Trial/tree/issue/10

**Comment by Darkirius** [comment]
GPUVideoEncoderException
GPUVideoEncoder.SfMovieRecord.StartMovieRecord (System.String outputPath, System.String fileTitle, IntPtr texture, Int32 fps, Boolean withAudio, UInt64 audioDeviceIndex) (at Assets/GPUVideoEncoder/Scripts/SfMovieRecord.cs:84)
GPUVideoEncoder.MovieRecordCamera.StartMovieRecord () (at Assets/GPUVideoEncoder/Scripts/MovieRecordCamera.cs:54)
UnityEngine.Events.InvokableCall.Invoke (System.Object[] args) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:144)
UnityEngine.Events.InvokableCallList.Invoke (System.Object[] parameters) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:621)
UnityEngine.Events.UnityEventBase.Invoke (System.Object[] parameters) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:756)
UnityEngine.Events.UnityEvent.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent_0.cs:53)
UnityEngine.UI.Button.Press () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:35)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:44)
UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:52)
UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickHandler](UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:269)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by Darkirius** [comment]
i buy plugin. plz update plugin in assets store.

**Comment by satoshi-maemoto** [comment]
Hi @Darkirius 
I submitted update to AssetStore now.
Please wait for the end of review.
Thank you.
