### ISSUE TITLE
Quality

### ISSUE THREAD

**Issue by Darkirius** [SystemFriend/GPUVideoEncoder-Trial#8]
How to change the compression ratio of the video?
What frame rate video?
How to change the frame rate video?

**Comment by Darkirius** [comment]
How to change the colour formate?

**Comment by Darkirius** [comment]
![color-format](https://cloud.githubusercontent.com/assets/19587746/16204674/afaae7d0-3728-11e6-90cc-c3e5adb3f91a.png)

**Comment by Darkirius** [comment]
It's important for me. When the fix?

**Comment by satoshi-maemoto** [comment]
@Darkirius 
Thak you for your information.
I will check this today.

**Comment by satoshi-maemoto** [comment]
@Darkirius 
I fixed color tone difference problem now.
this update merged to master.

I consider.
another options will support at paid version.
